name: vsc-cv
services:
  app:
    image: vsc-cv
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VSC_CV_CONFIG_FILE:-./config.toml}:/app/config/config.toml
    ports:
      - ${VSC_CV_PORT:-8080}:8080
    healthcheck:
      test: ['CMD-SHELL', 'curl -f 127.0.0.1:8080/cv-api/v1']
      interval: 20s
      timeout: 3s
      retries: 5
    # depends_on:
    #   mongo:
    #     condition: service_healthy

  mongo:
    image: mongo:8.0.4
    profiles:
      - db
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - mongod:/data/db
      - mongoconfig:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      retries: 5
      timeout: 5s

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    environment:
      BASE_URL: /docs
      URLS: >-
        [{url: "http://localhost:8080/cv-api/v1/", name: "VSC Contract Verifier"}]

  cloudflared:
    image: cloudflare/cloudflared:latest
    profiles:
      - cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN:-}
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  mongod:
  mongoconfig:
